export const CHANGE_EDIT_POST = 'CHANGE_EDIT_POST'
export const CONTENT_EDIT = 'CONTENT_EDIT'

export const CREAT_NEW_POST = 'CREAT_NEW_POST'
export const CREAT_NEW_POST_CONTENT = 'CREAT_NEW_POST_CONTENT'

export const CHANG_TEXT_COMMENT = 'CHANG_TEXT_COMMENT'

export const MODAL_SHOW = 'MODAL_SHOW'

export const SET_INDEX_EDIT_POST = 'SET_INDEX_EDIT_POST'
