export const ON_CHANGE_CONTROL_NAME = 'ON_CHANGE_CONTROL_NAME'

export const AUTHORIZATION_TOKEN_USER_ID = 'AUTHORIZATION_TOKEN_USER_ID'
export const AUTHORIZATION_TOKEN_TRUE = 'AUTHORIZATION_TOKEN_TRUE'
export const GET_PHOTOS_RESPONSE = 'GET_PHOTOS_RESPONSE'

export const CLIAN_STATE = 'CLIAN_STATE'
